# Generated by Django 4.1 on 2023-11-11 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0013_delete_employeeshift'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reg', models.DateField(verbose_name='Fecha de registro')),
                ('entry_time', models.TimeField(verbose_name='Hora entrada')),
                ('departure_time', models.TimeField(verbose_name='Hora salida')),
                ('holiday', models.BooleanField(default=False, verbose_name='Feriado')),
                ('total_hours', models.FloatField(default=0, verbose_name='Total horas')),
                ('valor_hours', models.FloatField(default=0, verbose_name='Valor horas')),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.employee')),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
    ]
