# Generated by Django 4.1 on 2023-10-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reg', models.DateField(verbose_name='Fecha de registro')),
                ('entry_time', models.TimeField(verbose_name='Hora entrada')),
                ('departure_time', models.TimeField(verbose_name='Hora salida')),
                ('holiday', models.BooleanField(default=False, verbose_name='Feriado')),
                ('total_hours', models.IntegerField(default=0, verbose_name='Total horas')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='identification',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Employee_Shift',
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.employee'),
        ),
    ]
