# Generated by Django 4.1 on 2023-10-14 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_hours_deperturetime_alter_hours_entrytime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reg', models.DateField(verbose_name='Fecha de registro')),
                ('entry_time', models.DateTimeField(verbose_name='Hora entrada')),
                ('deperture_time', models.DateTimeField(verbose_name='hora salida')),
                ('holiday', models.BooleanField(default=False, verbose_name='Feriado')),
                ('totalHours', models.IntegerField(verbose_name='Total horas')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='cityOfFresidence',
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(default=0, max_length=50, verbose_name='Ciudad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='numberphone',
            field=models.CharField(max_length=10, verbose_name='Numero telefonico'),
        ),
        migrations.DeleteModel(
            name='hours',
        ),
        migrations.AddField(
            model_name='employee_hours',
            name='identificationEmployee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.employee', verbose_name='identificacion del empleado'),
        ),
    ]
