# Generated by Django 4.1 on 2023-10-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_employeeshift_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshift',
            name='valor_hours',
            field=models.FloatField(default=0, verbose_name='Total horas'),
        ),
    ]
