# Generated by Django 4.1 on 2023-10-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_employee_hours_remove_employee_cityoffresidence_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee_Hours',
            new_name='Employee_Shift',
        ),
    ]
