# Generated by Django 4.1 on 2023-10-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeshift',
            name='valor_hours',
            field=models.FloatField(default=0, verbose_name='Valor horas'),
        ),
    ]
