# Generated by Django 4.1 on 2023-10-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_rename_employee_hours_employee_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_shift',
            name='deperture_time',
            field=models.TimeField(verbose_name='hora salida'),
        ),
        migrations.AlterField(
            model_name='employee_shift',
            name='entry_time',
            field=models.TimeField(verbose_name='Hora entrada'),
        ),
    ]
