# Generated by Django 4.1 on 2023-10-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_alter_employeeshift_valor_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
