# Generated by Django 4.1 on 2023-10-14 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_alter_employee_shift_deperture_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_shift',
            name='identificationEmployee',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_shift',
            name='employee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='empleados.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='identification',
            field=models.CharField(max_length=20),
        ),
    ]
