# Generated by Django 4.1 on 2023-10-24 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_employee_is_deleted_employeeshift_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_id']},
        ),
    ]
