# Generated by Django 4.1 on 2023-10-24 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeshift',
            options={'ordering': ['employee_id']},
        ),
    ]
