# Generated by Django 4.1 on 2023-10-24 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0009_alter_employeeshift_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['email']},
        ),
    ]
