# Generated by Django 4.1 on 2023-11-11 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0012_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeShift',
        ),
    ]
